# Generated by Django 3.2.12 on 2022-02-27 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaveapp', '0003_auto_20220226_0225'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='requested_days',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
